### ISSUE TITLE
Out Animations

### ISSUE THREAD

**Issue by trekfan42** [murikistudio/simple-gui-transitions#1]
Is there a way to implement a reverse animation using a duplicate animation on the same node and calling that instead?

I have an app that I was hoping to animate slide rights to go to the next page and have the current page animate slide left when leaving?

I'm trying to figure out if there is a way to use what you've built to pull that off...

**Comment by joelgomes1994** [comment]
Hi! I'm not sure if I understand what you mean... Is it like the example below?

https://user-images.githubusercontent.com/19820741/212561885-f9b1eb14-5e04-4c5a-86f1-bad0f0269eeb.mp4

You can actually mix several animations in the same layout, to animate parts of the layout with different animations, like so:

https://user-images.githubusercontent.com/19820741/212561651-184459f9-daab-4d9b-b82b-585135c912fb.mp4

**Comment by trekfan42** [comment]
yeah exactly, I cant figure out how to make that happen, when I trigger going to a new page, it just slides back out the way it came by default

**Comment by joelgomes1994** [comment]
Yes, that's the behavior, one single animation back and forth. But I surely can implement different animations both for entering and leaving the screen, that shouldn't be difficult (for example, 'Slide Left' for entering the screen, 'Slide Right' for leaving the screen).

**Comment by trekfan42** [comment]
Yeah I think 2 fields one for the enter animation and one for the leave animation would be great!
 Here is the app I am working on that is using it: https://trekfan42.github.io/MiniGolf_Scorecard/

I want to use the scroll right to enter and the scroll left when leaving to make it like a carousel effect.

**Comment by joelgomes1994** [comment]
Alright, I'll work on this feature. Thanks for the feature request!

**Comment by joelgomes1994** [comment]
@trekfan42 I've implemented the requested feature and other improvements. The updated plugin is available at the [releases page](https://github.com/murikistudio/simple-gui-transitions/releases).

https://user-images.githubusercontent.com/19820741/212794803-7a4e7dbc-468c-463d-bf34-c98717275056.mp4

**Comment by trekfan42** [comment]
you are awesome! thanks so much!

**Comment by trekfan42** [comment]
@joelgomes1994 I'm loving the new array node selection as well!

**Comment by joelgomes1994** [comment]
> @joelgomes1994 I'm loving the new array node selection as well!

Yeah, that's a pretty handy feature, gives us more control. I'm glad you liked it. :wink:

**Comment by trekfan42** [comment]
I want to implement conditional animations, so I think I may have to create a Global.currentPage and iterate it depending on the screen I am on, then on my root scene node script do a conditional check of what page it is on and assign the animation enter and leave based on that...

so:
[Page 1] < Page 2 < Page 3
but if you are on Page 2 then:
Page 1 > [Page 2] < Page 3
if that makes sense...

Once that's done I'm all set!

**Comment by trekfan42** [comment]
@joelgomes1994 any idea if this is a bug or if I'm doing something wrong?

**Comment by joelgomes1994** [comment]
Well, it's more of a non-implemented feature: the addon does not support dynamic addition of nodes yet.
As I develop the addon especifically to meet the needs of @murikistudio's projects, I'm sure I'll eventually add this feature soon (for example, to animate a scoreboard with dynamic scores). For now, maybe just fading or scaling the parent container should do the job.

**Comment by trekfan42** [comment]
@joelgomes1994  okay, I understand, I was just curious if maybe something broke since sliding animation for whole node groups worked in the last build, but not this one...
Now slide animations don't work unless you specify nodes part of the new array feature...

**Comment by joelgomes1994** [comment]
There's actually a reason: the previous release performed the slide animations on the the controls rect_position, allowing parents to move around and take children with them. That was cool, but if you resized the screen all the positions and animations would break (except when using `display/window/stretch/mode` to `2d`). The current slide animations use a shader to move the vertices, fixing the screen resizing problem but disabling the parent-children translation. Maybe I could add an options to select the shader or the absolute rect_position, so the user could pick his poison.

**Comment by trekfan42** [comment]
I use animating rec_position for my background texturerect, I haven't had any issues with respecting to stretching and my project is set to viewport

**Comment by joelgomes1994** [comment]
When the screen is resized, the addon would lose track of the original position of the controls to  animate them back. That doesn't happen on the stretch mode set to `2d`.

![image](https://user-images.githubusercontent.com/19820741/213333204-ca6bd80e-a975-4bbd-bb7d-4c9f7420b82f.png)

https://user-images.githubusercontent.com/19820741/213332825-d3359b7d-15a9-4744-9c69-5e8f20d83d1a.mp4

**Comment by trekfan42** [comment]
wow, I guess I am going crazy, I don't remember having that issue...
Maybe it has something to do with how my nodes are parented vs yours?
Oh well, no big, I may go in and try to manually set the instanced scenes to animate on add.

Thanks again for this great addon!
