### ISSUE TITLE
Godot Asset Library

### ISSUE THREAD

**Issue by coppolaemilio** [murikistudio/simple-gui-transitions#4]
Hey, I'm sorry, but still can't figure out why I can't approve your latest changes to the Godot Asset Lib. I'll try to get in touch with other members of the team to see if we can fix the issue.

**Comment by joelgomes1994** [comment]
Ok, thanks!

**Comment by coppolaemilio** [comment]
It's not that sophisticated as far as I know 😅 
We are still trying to figure out why it fails.

**Comment by coppolaemilio** [comment]
We were able to approve it, but there wan an empty field (`Type`) on the new video submitted.

![image](https://user-images.githubusercontent.com/2206700/214588045-d471ed38-b92c-483e-abed-dc29381ea107.png)

Are you using an automated system to publish the updates or our website?

**Comment by coppolaemilio** [comment]
No problem! Closing this now, hope we don't have the issue again in the future. Cheers!
